In [1]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [2]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[46:104]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
46                 5.1               3.8                1.6               0.2   
47                 4.6               3.2                1.4               0.2   
48                 5.3               3.7                1.5               0.2   
49                 5.0               3.3                1.4               0.2   
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
55                 5.7               2.8                4.5               1.3   
56                 6.3               3.3                4.7               1.6   
57                 4.9               2.4                3.3               1.0   
58                 6.6               2.9                4.6               1.3   
59                 5.2               2.7                3.9               1.4   
60                 5.0               2.0                3.5               1.0   
61                 5.9               3.0                4.2               1.5   
62                 6.0               2.2                4.0               1.0   
63                 6.1               2.9                4.7               1.4   
64                 5.6               2.9                3.6               1.3   
65                 6.7               3.1                4.4               1.4   
66                 5.6               3.0                4.5               1.5   
67                 5.8               2.7                4.1               1.0   
68                 6.2               2.2                4.5               1.5   
69                 5.6               2.5                3.9               1.1   
70                 5.9               3.2                4.8               1.8   
71                 6.1               2.8                4.0               1.3   
72                 6.3               2.5                4.9               1.5   
73                 6.1               2.8                4.7               1.2   
74                 6.4               2.9                4.3               1.3   
75                 6.6               3.0                4.4               1.4   
76                 6.8               2.8                4.8               1.4   
77                 6.7               3.0                5.0               1.7   
78                 6.0               2.9                4.5               1.5   
79                 5.7               2.6                3.5               1.0   
80                 5.5               2.4                3.8               1.1   
81                 5.5               2.4                3.7               1.0   
82                 5.8               2.7                3.9               1.2   
83                 6.0               2.7                5.1               1.6   
84                 5.4               3.0                4.5               1.5   
85                 6.0               3.4                4.5               1.6   
86                 6.7               3.1                4.7               1.5   
87                 6.3               2.3                4.4               1.3   
88                 5.6               3.0                4.1               1.3   
89                 5.5               2.5                4.0               1.3   
90                 5.5               2.6                4.4               1.2   
91                 6.1               3.0                4.6               1.4   
92                 5.8               2.6                4.0               1.2   
93                 5.0               2.3                3.3               1.0   
94                 5.6              

# Approach 1: Use train_test_split and manually tune parameters by trial and error

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3)

In [4]:
model = svm.SVC(kernel = 'rbf', C = 30, gamma = 'auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9333333333333333

# Approach 2: Use K Fold Cross Validation

# Manually try suppling model with different parameters to cross_val_score function with 5 fold cross validation.

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
cross_val_score(svm.SVC(kernel = 'linear', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [7]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 20, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

# Above approach is tiresome and very manual. We can use for loop as an alternative

In [9]:
import numpy as np
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel = kval, C = cval, gamma = 'auto'), iris.data, iris.target, cv = 5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

# from above results we can say that rbf with C = 1 or 10 or linear with C = 1 will give best performance

# Approach 3: Use GridSearchCV

In [10]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma = 'auto'), {
    'C' : [1, 10, 20],
    'kernel' : ['rbf', 'linear']
}, cv = 5, return_train_score = False)
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00139513, 0.00079818, 0.00099683, 0.001403  , 0.00059867,
        0.00059147]),
 'std_fit_time': array([4.88403205e-04, 3.99088899e-04, 2.46852476e-06, 1.01498136e-03,
        4.88812374e-04, 4.83104135e-04]),
 'mean_score_time': array([0.00059891, 0.00019965, 0.00100765, 0.00039926, 0.00039907,
        0.00040512]),
 'std_score_time': array([4.89006049e-04, 3.99303436e-04, 1.60039792e-05, 4.88992021e-04,
        4.88755398e-04, 4.96269481e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [11]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001395      0.000488         0.000599        0.000489       1   
1       0.000798      0.000399         0.000200        0.000399       1   
2       0.000997      0.000002         0.001008        0.000016      10   
3       0.001403      0.001015         0.000399        0.000489      10   
4       0.000599      0.000489         0.000399        0.000489      20   
5       0.000591      0.000483         0.000405        0.000496      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [12]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [13]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_required_parameters',
 '_run_search',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score

In [14]:
clf.best_score_

0.9800000000000001

In [15]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [16]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'), {
    'C' : [1, 10, 20],
    'kernel' : ['rbf', 'linear']
}, cv = 5, return_train_score = False, n_iter = 2)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf             0.98
1       1          rbf             0.98

# Now, How about different models with different hyperparameters ?

In [17]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [18]:
model_params = {
    'svm' : {
        'model' : svm.SVC(gamma = 'auto'),
        'params' : {
            'C' : [1, 10, 20],
            'kernel' : ['rbf', 'linear']
        }
    },
    'random_forest' : {
        'model' : RandomForestClassifier(),
        'params' : {
            'n_estimators' : [1, 5, 10]
        }
    },
    'logistic_regression' : {
        'model' : LogisticRegression(solver = 'liblinear', multi_class = 'auto'),
        'params' : {
            'C' : [1, 5, 10]
        }
    }
}

In [19]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv = 5, return_train_score = False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_
    })

In [20]:
df = pd.DataFrame(scores, columns = ['model', 'best_score', 'best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}