In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [16]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9796296296296296

In [9]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9944444444444445

In [19]:
rfc = RandomForestClassifier(n_estimators = 50)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.9796296296296296

In [ ]:
# INSTEAD OF USING THIS WE USE K-FOLD.
#BECAUSE EACH TIME WE RUN TEST_TRAIN_SPLIT, The Train and test data got change.

In [11]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [15]:
get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test)

0.9796296296296296

In [17]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9944444444444445

In [18]:
get_score(RandomForestClassifier(n_estimators = 50), X_train, X_test, y_train, y_test)

0.975925925925926

In [ ]:
# Another Way is StratifiedKFold

In [20]:
from sklearn.model_selection import StratifiedKFold

In [26]:
scores_lr = []
scores_svc = []
scores_rfc = []

for train_index, test_index in kf.split(digits.data):
    
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    scores_lr.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    
    scores_svc.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    
    scores_rfc.append(get_score(RandomForestClassifier(n_estimators = 50), X_train, X_test, y_train, y_test))

In [24]:
scores_lr

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [27]:
scores_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [28]:
scores_rfc

[0.9248747913188647, 0.9398998330550918, 0.9198664440734557]

In [ ]:
# Insted of doing Cell-26 we can simply use cross_val_score

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [31]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators = 50), digits.data, digits.target)

array([0.92777778, 0.9       , 0.96657382, 0.9637883 , 0.92479109])