In [14]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

# Logistic Regression

In [15]:
lr = cross_val_score(LogisticRegression(max_iter=10000), iris.data, iris.target)
lr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
np.average(lr)

0.9733333333333334

# Support Vector Machine

In [17]:
svm = cross_val_score(SVC(max_iter=10000), iris.data, iris.target)
svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [18]:
np.average(svm)

0.9666666666666666

# Random Forest Classifier

In [19]:
rfc = cross_val_score(RandomForestClassifier(n_estimators=50), iris.data, iris.target)
rfc

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [20]:
np.average(rfc)

0.9533333333333334